### ISSUE TITLE
data component in paths

### ISSUE THREAD

**Issue by vid** [solid-lite/server#1]
Can you explain why post and head paths have `/data` prepended, whereas get, put and delete don't? 

Thanks!

**Comment by vid** [comment]
I'd like to finish up some dev this w/e, @melvincarvalho  any clarification here? Thanks!

**Comment by melvincarvalho** [comment]
Could provide more detail on your issue?

Where is the source of your implementation?

**Comment by vid** [comment]
Hi, it's here https://github.com/withhaibun/solid-lite

[this](https://github.com/withhaibun/solid-lite/blob/main/src/lib/haibunSolidLite.ts) is a direct adaptation of this repo's [index.js](https://github.com/solid-lite/server/blob/gh-pages/index.js)

**Comment by melvincarvalho** [comment]
A lot of guess where going on here, but does this change help?

https://github.com/solid-lite/server/commit/a2c005a8f7654a846e0e1975abea63de2e203fcd

`data` has no significance in solid-lite, just a hard coded default of where to store data

**Comment by vid** [comment]
Yes (-: I was just comparing the implementation to the spec, and didn't see if /data was important somehow.
