### ISSUE TITLE
not supporting OPTIONS 

### ISSUE THREAD

**Issue by vid** [solid-lite/server#2]
I think the sample implementation is not returning any values for OPTIONS for non-CORS routes, as [implied by the spec](https://github.com/solid-lite/draft-spec#:~:text=Servers%20MUST%20support%20the%20HTTP%20GET%2C%20HEAD%20and%20OPTIONS%20methods%20%5BRFC7231%5D%20for%20clients%20to%20read%20resources%20or%20to%20determine%20communication%20options).

**Comment by melvincarvalho** [comment]
any more details on this?

**Comment by vid** [comment]
This is probably a misinterpretation on my part, closing the issue.
